// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX5u0pO5ZpliieJ48FLCUjA47qws47j_o',
    appId: '1:354871607864:web:c63df56c2c2aa17c9b1ccd',
    messagingSenderId: '354871607864',
    projectId: 'lab3-mealsdb',
    authDomain: 'lab3-mealsdb.firebaseapp.com',
    storageBucket: 'lab3-mealsdb.firebasestorage.app',
    measurementId: 'G-1XV9T3XNSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYs5yd66It31G-HwUDC-jiJBITSQUFEeo',
    appId: '1:354871607864:android:010954e6ee5302079b1ccd',
    messagingSenderId: '354871607864',
    projectId: 'lab3-mealsdb',
    storageBucket: 'lab3-mealsdb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX5u0pO5ZpliieJ48FLCUjA47qws47j_o',
    appId: '1:354871607864:web:619b9e3e341960af9b1ccd',
    messagingSenderId: '354871607864',
    projectId: 'lab3-mealsdb',
    authDomain: 'lab3-mealsdb.firebaseapp.com',
    storageBucket: 'lab3-mealsdb.firebasestorage.app',
    measurementId: 'G-4Z3EYJ1JB1',
  );
}
